### PR TITLE
workaround for mimemagic

### PR DESCRIPTION
**Pull request by benr75**
Hi - the current deploy to Heroku is broken as the mimemagic gem referenced no longer exists. This work around allowed me to deploy. A longer term fix would be to upgrade the Rails version.

### CODE REVIEW

**Comment by web20opensource** [comment]
Same happening to me today

      Fetching gem metadata from https://rubygems.org/............
       Your bundle is locked to mimemagic (0.3.5) from rubygems repository
       https://rubygems.org/ or installed locally, but that version can no longer be
       found in that source. That means the author of mimemagic (0.3.5) has removed it.
       You'll need to update your bundle to a version other than mimemagic (0.3.5) that
       hasn't been removed in order to install.
       Bundler Output: Fetching gem metadata from https://rubygems.org/............
       Your bundle is locked to mimemagic (0.3.5) from rubygems repository
       https://rubygems.org/ or installed locally, but that version can no longer be
       found in that source. That means the author of mimemagic (0.3.5) has removed it.
       You'll need to update your bundle to a version other than mimemagic (0.3.5) that
       hasn't been removed in order to install.
 !
 !     Failed to install gems via Bundler.
 !
 !     Push rejected, failed to compile Ruby app.
 !     Push failed

**Comment by web20opensource** [comment]
Hi @benr75,

 I tried your fix but still is not going through in the setup phase when trying to deploy in heroku

 Is it working for you? 

Thanks.

**Comment by benr75** [comment]
@web20opensource glad you figured that out. If anyone else stumbles along this be sure to update the readme in your forked repo to point to the new template so the button works to deploy or else it will continue to grab the solidusio repo. 

https://github.com/benr75/solidus-example-app/commit/afafbcf1a9ef9895c88c5c3358f8881dc6cff0fd

**Comment by web20opensource** [comment]
Exactly that what I did :)

https://github.com/web20opensource/solidus-example-app/commit/76b0647a1c527dcec4a252b485626c59cf560260

**Pull request closed without merging**
